line-length = 100

[lint]
select = ["E", "F", "I"]  # Базовые проверки: ошибки, импорты, сортировка
ignore = ["E501"]          # Игнорировать длину строки

[lint.per-file-ignores]
"__init__.py" = ["F401"]   # Разрешить неиспользуемые импорты в __init__.py
